#!/bin/bash

set -ex

# LANG=zh_yue
LANG=zh

# Overall script to extract the stuff. The final output is in extracted.txt

if [ ! -f "$LANG"wiki-latest-categorylinks.sql ]; then
  curl -O https://dumps.wikimedia.org/"$LANG"wiki/latest/"$LANG"wiki-latest-categorylinks.sql.gz
  gunzip -k "$LANG"wiki-latest-categorylinks.sql.gz
fi

if [ ! -f "$LANG"wiki-latest-page.sql ]; then
  curl -O https://dumps.wikimedia.org/"$LANG"wiki/latest/"$LANG"wiki-latest-page.sql.gz
  gunzip -k "$LANG"wiki-latest-page.sql.gz
fi
if [ ! -f "$LANG"wiki-latest-pagelinks.sql.gz ]; then
  curl -O https://dumps.wikimedia.org/"$LANG"wiki/latest/"$LANG"wiki-latest-pagelinks.sql.gz
  gunzip -k "$LANG"wiki-latest-pagelinks.sql.gz
fi

# rm -vf "$LANG"wiki.sqlite3 # clear derived file

if [ ! -f "$LANG"wiki.sqlite3 ]; then
    ./hack-mangle.py "$LANG"wiki-latest-categorylinks.sql categorylinks
    sqlite3 "$LANG"wiki.sqlite3 < "$LANG"wiki-latest-categorylinks.sql.fixed

    ./hack-mangle.py "$LANG"wiki-latest-page.sql page
    sqlite3 "$LANG"wiki.sqlite3 < "$LANG"wiki-latest-page.sql.fixed

    ./hack-mangle.py "$LANG"wiki-latest-pagelinks.sql pagelinks
    sqlite3 "$LANG"wiki.sqlite3 < "$LANG"wiki-latest-pagelinks.sql.fixed

    echo 'CREATE INDEX "category_from" ON categorylinks (cl_from);' | sqlite3 "$LANG"wiki.sqlite3
    echo 'CREATE INDEX "category_to" ON categorylinks (cl_to);' | sqlite3 "$LANG"wiki.sqlite3
    echo 'CREATE INDEX "pagelink_to_title" ON pagelinks (pl_title);' | sqlite3 "$LANG"wiki.sqlite3
fi

set +x

sqlite3 "$LANG"wiki.sqlite3 < query.sql > "$LANG"wiki.fictional-characters.txt
cat "$LANG"wiki.fictional-characters.txt

# On macOS the sort tries to be smart...
# LC_ALL=C sort temp_names.txt | uniq > extracted.txt
